# DALHA Wada display-name mapping
# original_name: Wada 원본 영문명 (팔레트 옆 표시)
# name_ko: 한국 패션 문장용 일반 색상명
# standard_color: 옷장 매칭용 넓은 색상 분류

WADA_COLOR_KO = {'#004f46': {'name_ko': '다크 청록', 'original_name': 'Dusky Green', 'standard_color': '청록'},
 '#005b8d': {'name_ko': '다크 블루', 'original_name': 'Helvetia Blue', 'standard_color': '블루'},
 '#006eb8': {'name_ko': '딥 블루', 'original_name': 'Blue', 'standard_color': '블루'},
 '#007190': {'name_ko': '딥 블루', 'original_name': 'Antwarp Blue', 'standard_color': '블루'},
 '#00908a': {'name_ko': '딥 청록', 'original_name': 'Light Porcelain Green', 'standard_color': '청록'},
 '#0093a5': {'name_ko': '딥 청록', 'original_name': 'Cerulian Blue', 'standard_color': '청록'},
 '#00978d': {'name_ko': '딥 청록', 'original_name': 'Benzol Green', 'standard_color': '청록'},
 '#00b49b': {'name_ko': '청록색', 'original_name': 'Sea Green', 'standard_color': '청록'},
 '#051230': {'name_ko': '딥 네이비', 'original_name': 'Deep Indigo', 'standard_color': '네이비'},
 '#064f6e': {'name_ko': '다크 블루', 'original_name': "Vandar Poel's Blue", 'standard_color': '블루'},
 '#099197': {'name_ko': '딥 청록', 'original_name': 'Green Blue', 'standard_color': '청록'},
 '#111314': {'name_ko': '블랙', 'original_name': 'Black', 'standard_color': '블랙'},
 '#112f2c': {'name_ko': '다크 청록', 'original_name': 'Deep Slate Green', 'standard_color': '청록'},
 '#12354e': {'name_ko': '딥 네이비', 'original_name': 'Dark Tyrian Blue', 'standard_color': '블루'},
 '#1a7444': {'name_ko': '다크 그린', 'original_name': 'Diamine Green', 'standard_color': '그린'},
 '#1c4286': {'name_ko': '딥 블루', 'original_name': 'Deep Lyons Blue', 'standard_color': '블루'},
 '#1e0e3f': {'name_ko': '다크 바이올렛', 'original_name': 'Dull Violet Black', 'standard_color': '퍼플'},
 '#34454c': {'name_ko': '다크 블루', 'original_name': 'Slate Color', 'standard_color': '블루'},
 '#40456a': {'name_ko': '딥 네이비', 'original_name': 'Violet Blue', 'standard_color': '네이비'},
 '#42533e': {'name_ko': '딥 그린', 'original_name': 'Blackish Olive', 'standard_color': '그린'},
 '#437742': {'name_ko': '딥 그린', 'original_name': 'Cossack Green', 'standard_color': '그린'},
 '#4b3317': {'name_ko': '다크 브라운', 'original_name': 'Vandyke Brown', 'standard_color': '브라운'},
 '#4e1d4c': {'name_ko': '다크 퍼플', 'original_name': 'Dusky Madder Violet', 'standard_color': '퍼플'},
 '#4f4086': {'name_ko': '딥 바이올렛', 'original_name': 'Violet', 'standard_color': '퍼플'},
 '#501345': {'name_ko': '다크 퍼플', 'original_name': 'Cotinga Purple', 'standard_color': '퍼플'},
 '#555832': {'name_ko': '다크 옐로', 'original_name': 'Lincoln Green', 'standard_color': '옐로'},
 '#59256a': {'name_ko': '딥 퍼플', 'original_name': 'Red Violet', 'standard_color': '퍼플'},
 '#5a82b3': {'name_ko': '블루', 'original_name': 'Olympic Blue', 'standard_color': '블루'},
 '#62c6bf': {'name_ko': '청록', 'original_name': 'Venice Green', 'standard_color': '청록'},
 '#642d5e': {'name_ko': '딥 퍼플', 'original_name': 'Violet Red', 'standard_color': '퍼플'},
 '#644b1e': {'name_ko': '다크 브라운', 'original_name': 'Sepia', 'standard_color': '브라운'},
 '#6450a1': {'name_ko': '블루 바이올렛', 'original_name': 'Blue Violet', 'standard_color': '퍼플'},
 '#653514': {'name_ko': '다크 오렌지', 'original_name': 'Mars Brown Tobacco', 'standard_color': '오렌지'},
 '#66629c': {'name_ko': '블루', 'original_name': 'Dark Soft Violet', 'standard_color': '블루'},
 '#6b7140': {'name_ko': '딥 옐로', 'original_name': 'Olive Green', 'standard_color': '옐로'},
 '#6d4145': {'name_ko': '딥 레드', 'original_name': 'Vistoris Lake', 'standard_color': '레드'},
 '#71502f': {'name_ko': '딥 브라운', 'original_name': 'Pale Raw Umber', 'standard_color': '브라운'},
 '#719470': {'name_ko': '그린', 'original_name': 'Chromium Green', 'standard_color': '그린'},
 '#762c19': {'name_ko': '딥 오렌지', 'original_name': 'Madder Brown', 'standard_color': '오렌지'},
 '#78cdd0': {'name_ko': '청록', 'original_name': 'Calamine Blue', 'standard_color': '청록'},
 '#793327': {'name_ko': '딥 레드', 'original_name': "Hay's Russet", 'standard_color': '레드'},
 '#7a4456': {'name_ko': '딥 핑크', 'original_name': 'Taupe Brown', 'standard_color': '핑크'},
 '#7c4226': {'name_ko': '딥 오렌지', 'original_name': 'Brown', 'standard_color': '오렌지'},
 '#80719e': {'name_ko': '바이올렛', 'original_name': 'Dull Blue Violet', 'standard_color': '퍼플'},
 '#82241f': {'name_ko': '딥 레드', 'original_name': 'Vandyke Red', 'standard_color': '레드'},
 '#837e31': {'name_ko': '딥 옐로', 'original_name': 'Olive', 'standard_color': '옐로'},
 '#848061': {'name_ko': '딥 옐로', 'original_name': 'Light Grayish Olive', 'standard_color': '옐로'},
 '#84875e': {'name_ko': '딥 옐로', 'original_name': 'Krongbergs Green', 'standard_color': '옐로'},
 '#87c540': {'name_ko': '올리브', 'original_name': 'Night Green', 'standard_color': '올리브'},
 '#8b835b': {'name_ko': '딥 옐로', 'original_name': 'Dark Citrine', 'standard_color': '옐로'},
 '#8c4c62': {'name_ko': '딥 핑크', 'original_name': 'Veronia Purple', 'standard_color': '핑크'},
 '#8fa071': {'name_ko': '올리브', 'original_name': 'Rainette Green', 'standard_color': '올리브'},
 '#96874d': {'name_ko': '딥 브라운', 'original_name': 'Buffy Citrine', 'standard_color': '브라운'},
 '#97acc8': {'name_ko': '블루', 'original_name': 'Salvia Blue', 'standard_color': '블루'},
 '#9a72aa': {'name_ko': '라이트 모브', 'original_name': 'Light Mauve', 'standard_color': '퍼플'},
 '#a1a39a': {'name_ko': '그레이', 'original_name': 'Warm Gray', 'standard_color': '그레이'},
 '#a2b0ad': {'name_ko': '그레이', 'original_name': 'Mineral Gray', 'standard_color': '그레이'},
 '#a36aa5': {'name_ko': '퍼플', 'original_name': 'Aconite Violet', 'standard_color': '퍼플'},
 '#a5c8d1': {'name_ko': '라이트 블루', 'original_name': 'Light Glaucous Blue', 'standard_color': '블루'},
 '#a62c37': {'name_ko': '딥 레드', 'original_name': 'Carmine Red', 'standard_color': '레드'},
 '#a7d4e4': {'name_ko': '라이트 블루', 'original_name': "Pale King's Blue", 'standard_color': '블루'},
 '#a84222': {'name_ko': '딥 오렌지', 'original_name': 'Brick Red', 'standard_color': '오렌지'},
 '#ab2439': {'name_ko': '폼페이안 레드', 'original_name': 'Pompeian Red', 'standard_color': '레드'},
 '#afd472': {'name_ko': '올리브', 'original_name': 'Yellow Green', 'standard_color': '올리브'},
 '#b09f36': {'name_ko': '딥 옐로', 'original_name': 'Citrine', 'standard_color': '옐로'},
 '#b2b73e': {'name_ko': '옐로', 'original_name': 'Citron Yellow', 'standard_color': '옐로'},
 '#b4cdc2': {'name_ko': '라이트 그린', 'original_name': 'Glaucous Green', 'standard_color': '그린'},
 '#b59392': {'name_ko': '레드', 'original_name': 'Light Brown Drab', 'standard_color': '레드'},
 '#b5b1d8': {'name_ko': '라이트 블루', 'original_name': 'Grayish Lavender - A', 'standard_color': '블루'},
 '#b5decc': {'name_ko': '라이트 그린', 'original_name': 'Turquoise Green', 'standard_color': '그린'},
 '#b6bfc1': {'name_ko': '뉴트럴 그레이', 'original_name': 'Neutral Gray', 'standard_color': '그레이'},
 '#b73f74': {'name_ko': '핑크', 'original_name': 'Rosolanc Purple', 'standard_color': '핑크'},
 '#bb7125': {'name_ko': '시에나 브라운', 'original_name': 'Raw Sienna', 'standard_color': '브라운'},
 '#bce4e5': {'name_ko': '라이트 청록', 'original_name': 'Nile Blue', 'standard_color': '청록'},
 '#c0a9b3': {'name_ko': '핑크', 'original_name': 'Grayish Lavender - B', 'standard_color': '핑크'},
 '#c16b27': {'name_ko': '딥 오렌지', 'original_name': 'Orange Rufous', 'standard_color': '오렌지'},
 '#c19f2c': {'name_ko': '딥 브라운', 'original_name': 'Sulphine Yellow', 'standard_color': '브라운'},
 '#c1c494': {'name_ko': '옐로', 'original_name': 'Olive Buff', 'standard_color': '옐로'},
 '#c27544': {'name_ko': '오렌지', 'original_name': 'Cinnamon Rufous', 'standard_color': '오렌지'},
 '#c55347': {'name_ko': '레드', 'original_name': 'Etruscan Red', 'standard_color': '레드'},
 '#c56127': {'name_ko': '딥 오렌지', 'original_name': 'Vinaceous Tawny', 'standard_color': '오렌지'},
 '#c5a56e': {'name_ko': '머스타드', 'original_name': 'Isabella Color', 'standard_color': '머스타드'},
 '#c7d14f': {'name_ko': '옐로', 'original_name': 'Light Green Yellow', 'standard_color': '옐로'},
 '#ca92a8': {'name_ko': '핑크', 'original_name': 'Laelia Pink', 'standard_color': '핑크'},
 '#cc1236': {'name_ko': '딥 레드', 'original_name': 'Carmine', 'standard_color': '레드'},
 '#d1b0a7': {'name_ko': '라이트 오렌지', 'original_name': 'Fawn', 'standard_color': '오렌지'},
 '#d46d7a': {'name_ko': '레드', 'original_name': 'Old Rose', 'standard_color': '레드'},
 '#d6b43e': {'name_ko': '머스타드', 'original_name': 'Olive Ocher', 'standard_color': '머스타드'},
 '#d8a37b': {'name_ko': '오렌지', 'original_name': 'Ochraceous Salmon', 'standard_color': '오렌지'},
 '#d96629': {'name_ko': '오렌지', 'original_name': 'English Red', 'standard_color': '오렌지'},
 '#da525d': {'name_ko': '레드', 'original_name': 'Eugenia Red B', 'standard_color': '레드'},
 '#dd4027': {'name_ko': '레드', 'original_name': 'Red Orange', 'standard_color': '레드'},
 '#e0b3b6': {'name_ko': '카메오 핑크', 'original_name': 'Cameo Pink', 'standard_color': '레드'},
 '#e2b540': {'name_ko': '머스타드', 'original_name': 'Yellow Ocher', 'standard_color': '머스타드'},
 '#ebd3a2': {'name_ko': '아이보리', 'original_name': 'Ivory Buff', 'standard_color': '머스타드'},
 '#eeb480': {'name_ko': '머스타드', 'original_name': 'Pinkish Cinnamon', 'standard_color': '머스타드'},
 '#f15a30': {'name_ko': '오렌지', 'original_name': 'Peach Red', 'standard_color': '오렌지'},
 '#f27291': {'name_ko': '레드', 'original_name': 'Spinel Red', 'standard_color': '레드'},
 '#f37420': {'name_ko': '오렌지', 'original_name': 'Orange', 'standard_color': '오렌지'},
 '#f37f94': {'name_ko': '라이트 레드', 'original_name': 'Eosine Pink', 'standard_color': '레드'},
 '#f3a257': {'name_ko': '머스타드', 'original_name': 'Golden Yellow', 'standard_color': '머스타드'},
 '#f48067': {'name_ko': '레드', 'original_name': 'Grenadine Pink', 'standard_color': '레드'},
 '#f58e84': {'name_ko': '라이트 레드', 'original_name': 'Coral Red', 'standard_color': '레드'},
 '#f5ecc2': {'name_ko': '페일 옐로', 'original_name': 'Sulpher Yellow', 'standard_color': '옐로'},
 '#f8b6ba': {'name_ko': '라이트 레드', 'original_name': 'Corinthian Pink', 'standard_color': '레드'},
 '#f8ed43': {'name_ko': '옐로', 'original_name': 'Lemon Yellow', 'standard_color': '옐로'},
 '#f99d1b': {'name_ko': '머스타드', 'original_name': 'Yellow Orange', 'standard_color': '머스타드'},
 '#fbe6a0': {'name_ko': '라이트 머스타드', 'original_name': 'Naples Yellow', 'standard_color': '머스타드'},
 '#fcb315': {'name_ko': '머스타드', 'original_name': 'Orange Yellow', 'standard_color': '머스타드'},
 '#fdc57e': {'name_ko': '시나몬 베이지', 'original_name': 'Cinnamon Buff', 'standard_color': '머스타드'},
 '#fdd4bd': {'name_ko': '페일 오렌지', 'original_name': 'Seashell Pink', 'standard_color': '오렌지'},
 '#ffdd00': {'name_ko': '옐로', 'original_name': 'Apricot Yellow', 'standard_color': '옐로'},
 '#ffefae': {'name_ko': '라이트 옐로', 'original_name': 'Pale Lemon Yellow', 'standard_color': '옐로'},
 '#fff200': {'name_ko': '옐로', 'original_name': 'Yellow', 'standard_color': '옐로'},
 '#ffffff': {'name_ko': '화이트', 'original_name': 'White', 'standard_color': '화이트'}}

def get_wada_color_ko(hex_value, fallback_name=''):
    value = WADA_COLOR_KO.get(hex_value.lower())
    if value:
        return value
    return {
        'original_name': fallback_name,
        'name_ko': fallback_name,
        'standard_color': '기타'
    }
