"""Export the generated food sheets and their explicit menu-to-image catalog.

Each source is an image atlas whose grid is specified in the manifest. This only resizes/encodes the generated
artwork for web delivery; menu ordering is preserved by the checked manifest.
Run from the repository root with --sources followed by the seven source PNGs.
Later artwork can replace these sources without changing recommendation logic.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "assets" / "food-thumbnails-v1"
MANIFEST = DEST / "manifest.json"


def build_catalog(manifest):
    cells = {}
    for sheet_index, sheet in enumerate(manifest["sheets"]):
        assert len(sheet["menus"]) == sheet["columns"] * sheet["rows"]
        for cell, name in enumerate(sheet["menus"]):
            assert name not in cells, f"Duplicate menu: {name}"
            cells[name] = [sheet_index, cell]
    for sheet in manifest["sheets"]:
        assert len(sheet["crop_rects"]) == len(sheet["menus"])
        for x, y, width, height in sheet["crop_rects"]:
            assert x >= 0 and y >= 0 and width > 0 and height > 0
            assert x + width <= sheet['columns'] * 128 and y + height <= sheet['rows'] * 128
    return {"version": manifest["version"], "columns": 7, "rows": 6,
            "files": [s["file"] for s in manifest["sheets"]],
            "sizes": [[s['columns'] * 128, s['rows'] * 128] for s in manifest['sheets']],
            "crops": [s["crop_rects"] for s in manifest["sheets"]], "menus": cells}


def check_catalog(catalog):
    sys.path.insert(0, str(ROOT / "backend"))
    from app.engine.services.simple_menu import eligible_menus
    from app.engine.services.daily_menu import DIET_MENU_POOL
    expected = {m.name for m in eligible_menus()} | {m.name for m in DIET_MENU_POOL}
    assert set(catalog["menus"]) == expected, {
        "missing": sorted(expected - catalog["menus"].keys()),
        "obsolete": sorted(catalog["menus"].keys() - expected),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sources", nargs="*")
    parser.add_argument("--catalog-only", action="store_true")
    parser.add_argument("--sheet-start", type=int, default=0,
                        help="Zero-based first sheet when exporting only new atlases")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    catalog = build_catalog(manifest)
    check_catalog(catalog)
    if args.sources:
        from PIL import Image
        sheets = manifest['sheets'][args.sheet_start:args.sheet_start+len(args.sources)]
        assert len(args.sources) == len(sheets)
        for source, sheet in zip(args.sources, sheets):
            with Image.open(source) as original:
                # Flatten alpha onto white for consistent website thumbnails.
                rgba = original.convert('RGBA')
                white = Image.new('RGBA', rgba.size, 'white')
                artwork = Image.alpha_composite(white, rgba).convert("RGB").resize(
                    (sheet["columns"] * 128, sheet["rows"] * 128),
                    Image.Resampling.LANCZOS)
            target = DEST / sheet["file"]
            for quality in (50, 42, 34, 26):
                artwork.save(target, "WEBP", quality=quality, method=6)
                if target.stat().st_size <= 80 * 1024:
                    break
            assert target.stat().st_size <= 80 * 1024, target
    if not args.catalog_only:
        from PIL import Image
        for file, dimensions in zip(catalog["files"], catalog['sizes']):
            target = DEST / file
            with Image.open(target) as image:
                assert image.format == "WEBP" and image.size == tuple(dimensions)
            assert target.stat().st_size <= 80 * 1024
    (DEST / "catalog.js").write_text(
        "// Generated by scripts/build_food_thumbnails.py; explicit catalog, no fuzzy matching.\n"
        "window.DALHA_FOOD_THUMBNAILS = "
        + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(json.dumps({"menus": len(catalog["menus"]), "sheets": len(catalog["files"]),
                      "image_bytes": sum((DEST / f).stat().st_size for f in catalog["files"]
                                         if (DEST / f).exists())}))


if __name__ == "__main__":
    main()
