"""Build public fictional report examples from the production renderers.

Run from the repository root: PYTHONPATH=backend:. python scripts/build_theme_examples.py
No account, payment, or persisted reading is read or written.
"""
from datetime import date, time
from pathlib import Path
import json
from app.engine.core.models import BirthInput
from app.engine.orchestrator import calculate_myeongri_core
from app.engine.services import (build_lifetime_career_report, build_lifetime_love_report,
    build_lifetime_wealth_report, build_lifetime_health_report, build_lifetime_study_report,
    build_compatibility_report)

core = calculate_myeongri_core(BirthInput(name='지우',gender='female',birth_date=date(1992,5,16),birth_time=time(8)), target_date=date(2026,10,1))
partner = calculate_myeongri_core(BirthInput(name='도윤',gender='male',birth_date=date(1990,10,4),birth_time=time(14)), target_date=date(2026,10,1))
reports = {}
def add(key, option, report):
    reports[key + ':' + option] = dict(report_key=key,report_title='[예시] '+report['title'],
        report_content=report['content'],narrative_version=report['narrative_version'],
        created_at='디자인 비교용',reading_context=dict(sub_option=option))
for option in ['직장인','취업/이직','사업가','창업']:
    add('business',option,build_lifetime_career_report(core,'지우',option))
for option in ['솔로','썸/짝사랑','연애중','기혼']:
    add('love',option,build_lifetime_love_report(core,'지우',option))
for key,builder in [('wealth',build_lifetime_wealth_report),('health',build_lifetime_health_report),('study',build_lifetime_study_report)]:
    add(key,'기본',builder(core,'지우'))
for relation in ['연인 / 결혼','동업 / 비즈니스','친구 / 지인']:
    add('gunghap',relation,build_compatibility_report(core,partner,'지우','도윤',relation))
output = Path('assets/theme-examples.js')
output.write_text('// Generated by scripts/build_theme_examples.py. Fictional examples; loaded on demand only.\n'
    'if (window.DALHA_DESIGN_SAMPLE) window.DALHA_THEME_EXAMPLES = '+json.dumps(reports,ensure_ascii=False,separators=(',',':'))+';\n')
print(f'{len(reports)} examples, {output.stat().st_size} bytes')
