"""Export the generated food sheets and their explicit menu-to-image catalog.

Each source is one 7-by-6 image atlas. This only resizes/encodes the generated
artwork for web delivery; menu ordering is preserved by the checked manifest.
Run from the repository root with --sources followed by the seven source PNGs.
Later artwork can replace these sources without changing recommendation logic.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "assets" / "food-thumbnails-v1"
MANIFEST = DEST / "manifest.json"


def build_catalog(manifest):
    cells = {}
    for sheet_index, sheet in enumerate(manifest["sheets"]):
        assert len(sheet["menus"]) == sheet["columns"] * sheet["rows"]
        for cell, name in enumerate(sheet["menus"]):
            assert name not in cells, f"Duplicate menu: {name}"
            cells[name] = [sheet_index, cell]
    for sheet in manifest["sheets"]:
        assert len(sheet["crop_rects"]) == len(sheet["menus"])
        for x, y, width, height in sheet["crop_rects"]:
            assert x >= 0 and y >= 0 and width > 0 and height > 0
            assert x + width <= 896 and y + height <= 768
    return {"version": manifest["version"], "columns": 7, "rows": 6,
            "files": [s["file"] for s in manifest["sheets"]],
            "crops": [s["crop_rects"] for s in manifest["sheets"]], "menus": cells}


def check_catalog(catalog):
    sys.path.insert(0, str(ROOT / "backend"))
    from app.engine.services.simple_menu import eligible_menus
    expected = {m.name for m in eligible_menus()}
    assert set(catalog["menus"]) == expected, {
        "missing": sorted(expected - catalog["menus"].keys()),
        "obsolete": sorted(catalog["menus"].keys() - expected),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sources", nargs="*")
    parser.add_argument("--catalog-only", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text())
    catalog = build_catalog(manifest)
    check_catalog(catalog)
    if args.sources:
        from PIL import Image
        assert len(args.sources) == len(manifest["sheets"])
        for source, sheet in zip(args.sources, manifest["sheets"]):
            with Image.open(source) as original:
                artwork = original.convert("RGB").resize(
                    (sheet["columns"] * 128, sheet["rows"] * 128),
                    Image.Resampling.LANCZOS)
            target = DEST / sheet["file"]
            for quality in (50, 42, 34, 26):
                artwork.save(target, "WEBP", quality=quality, method=6)
                if target.stat().st_size <= 80 * 1024:
                    break
            assert target.stat().st_size <= 80 * 1024, target
    if not args.catalog_only:
        from PIL import Image
        for file in catalog["files"]:
            target = DEST / file
            with Image.open(target) as image:
                assert image.format == "WEBP" and image.size == (896, 768)
            assert target.stat().st_size <= 80 * 1024
    (DEST / "catalog.js").write_text(
        "// Generated by scripts/build_food_thumbnails.py; explicit catalog, no fuzzy matching.\n"
        "window.DALHA_FOOD_THUMBNAILS = "
        + json.dumps(catalog, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(json.dumps({"menus": len(catalog["menus"]), "sheets": len(catalog["files"]),
                      "image_bytes": sum((DEST / f).stat().st_size for f in catalog["files"]
                                         if (DEST / f).exists())}))


if __name__ == "__main__":
    main()
